image: ghcr.io/graalvm/graalvm-ce:java11-21.0.0

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - code-analysis
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - exec-docker
  script: ./gradlew --build-cache assemble

unit-test:
  stage: test
  tags:
    - exec-docker
  script: ./gradlew test --continue

#integration-test:
#  stage: test
#  tags:
#    - exec-docker
#  script: ./gradlew integrationTest --continue

pmd:
  stage: code-analysis
  tags:
    - exec-docker
  script: ./gradlew pmdMain
  artifacts:
    paths:
     - build/reports/pmd/main.html
    expire_in: 5 days
    when: on_failure

checkstyle:
  stage: code-analysis
  tags:
    - exec-docker
  script: ./gradlew checkstyleMain
  artifacts:
    paths:
     - build/reports/checkstyle/main.html
    expire_in: 5 days
    when: on_failure

push-dockerhub-native:
  stage: deploy
  only:
    - schedules
  before_script:
    - gu install native-image
  tags:
    - exec-docker
  script: 
    - ./gradlew clean assemble -Dquarkus.package.type=native -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.name=trace-service-native -Dquarkus.container-image.additional-tags=$CI_COMMIT_SHORT_SHA -Dquarkus.native.additional-build-args="--initialize-at-run-time=org.apache.kafka.common.security.authenticator.SaslClientAuthenticator\\,org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin" -Dquarkus.container-image.username=$EXPLORVIZ_DOCKERHUB_USERNAME -Dquarkus.container-image.password=$EXPLORVIZ_DOCKERHUB_PASSWORD

push-dockerhub:
  stage: deploy
  only:
    - master
  except:
    - schedules
  tags:
    - exec-docker
  script: 
    - ./gradlew clean assemble -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.additional-tags=$CI_COMMIT_SHORT_SHA -Dquarkus.container-image.username=$EXPLORVIZ_DOCKERHUB_USERNAME -Dquarkus.container-image.password=$EXPLORVIZ_DOCKERHUB_PASSWORD